### ISSUE TITLE
accelerate.bat - not working, but..

### ISSUE THREAD

**Issue by MXZEHN** [olegchomp/TDDepthAnything#7]
Hi,
just wanted to let you know that the accelerate.bat throws an error, as it can not find python. 
However, it was suggested online to try "py" instead of "python" and that did work for me.
Maybe pother users have the same issue...
All the best
Stefan

**Comment by MXZEHN** [comment]
The next issue is that the component in TD throws an error,
from what i can tell, it doesn't find 
E:\DOWNLOADS/TDDepthAnything-main/TDDepthAnything\.venv/Lib/site-packages\torch\lib\shm.dll
However, that file is existing on that path...
I am on build 2023:11600

/project1/TDDepthAnything/script1_callbacks	Traceback (most recent call last):  File "/project1/TDDepthAnything/script1_callbacks", line 18, in onCookAttributeError: 'NoneType' object has no attribute 'run'	4478	227	abort	DAT
/project1/TDDepthAnything/DepthAnythingExt	Traceback (most recent call last):  File "/project1/TDDepthAnything/DepthAnythingExt", line 28    r = previousimport(*args, **kw)        ^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "E:\DOWNLOADS/TDDepthAnything-main/TDDepthAnything\.venv/Lib/site-packages\torch\__init__.py", line 141    raise errOSError: [WinError 126] The specified module could not be found. Error loading "E:\DOWNLOADS/TDDepthAnything-main/TDDepthAnything\.venv/Lib/site-packages\torch\lib\shm.dll" or one of its dependencies.	4478	227	abort	DAT

Any help appreciated!

All the best
Stefan

**Comment by NairoDorian** [comment]
I've got the same error, it's trying to import torch in DepthAnythingExt but it's not succeeding 
Edit: I've found https://github.com/pytorch/pytorch/issues/125109

Modifying the accelerate script to install the 2.2.x version of pytorch instead of 2.3.0 that was released last week fixed this issue for me

**Comment by olegchomp** [comment]
Thank you! Fixed with https://github.com/olegchomp/TDDepthAnything/commit/e5dfe397041de3b275b64a4cbf743f116023d408

**Comment by MXZEHN** [comment]
> Hi, just wanted to let you know that the accelerate.bat throws an error, as it can not find python. However, it was suggested online to try "py" instead of "python" and that did work for me. Maybe pother users have the same issue... All the best Stefan

this is still happening and the "py" instead of "python" trick still works
